In [1]:
import numpy as np

# Initialize random weights for a simple 2-neuron network
weights = np.random.rand(2, 1)  # 2 inputs, 1 output
inputs = np.array([0.5, 0.8])

# Weighted sum of inputs
weighted_sum = np.dot(inputs, weights)
print("Weighted Sum:", weighted_sum)


Weighted Sum: [0.97516935]


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Simple Perceptron model with 2 inputs and 1 output
model = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))  # One neuron, sigmoid activation

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Example data (XOR problem)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # Input
y = np.array([0, 1, 1, 0])  # Output

# Train the model
model.fit(X, y, epochs=1000, verbose=0)

# Predict
predictions = model.predict(X)
print("Predictions:", predictions)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Multi-layer Feedforward network with one hidden layer
model = Sequential()
model.add(Dense(8, input_dim=2, activation='relu'))  # Hidden layer with 8 neurons
model.add(Dense(1, activation='sigmoid'))  # Output layer

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Training data for a binary classification task
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  
y = np.array([0, 1, 1, 0])

model.fit(X, y, epochs=1000, verbose=0)

# Predict
predictions = model.predict(X)
print("Predictions:", predictions)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

# Simple RNN model for sequence processing
model = Sequential()
model.add(SimpleRNN(10, input_shape=(3, 1), activation='relu'))  # 10 neurons in RNN layer
model.add(Dense(1, activation='sigmoid'))  # Output layer

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Example input (sequence of 3 timesteps with 1 feature)
X = np.array([[[0.1], [0.2], [0.3]], [[0.2], [0.3], [0.4]]])
y = np.array([1, 0])

model.fit(X, y, epochs=100, verbose=0)

# Predict
predictions = model.predict(X)
print("Predictions:", predictions)


In [3]:
# Example of gradient descent to update weights
def gradient_descent(weights, learning_rate=0.1):
    # Simulate a simple gradient descent update step
    gradients = np.array([0.3, -0.2])  # Example gradients (just for demonstration)
    weights -= learning_rate * gradients
    return weights

weights = np.array([0.5, -0.3])
updated_weights = gradient_descent(weights)
print("Updated Weights:", updated_weights)


Updated Weights: [ 0.47 -0.28]


In [4]:
def binary_step(x):
    return np.where(x >= 0, 1, 0)

# Example usage
inputs = np.array([0.5, -0.2, 0.1])
outputs = binary_step(inputs)
print("Binary Step Outputs:", outputs)

Binary Step Outputs: [1 0 1]


In [5]:
def linear(x):
    return x  # Output is the same as input

# Example usage
inputs = np.array([0.5, -0.2, 0.1])
outputs = linear(inputs)
print("Linear Function Outputs:", outputs)


Linear Function Outputs: [ 0.5 -0.2  0.1]


In [6]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Example usage
inputs = np.array([0.5, -0.2, 0.1])
outputs = sigmoid(inputs)
print("Sigmoid Outputs:", outputs)


Sigmoid Outputs: [0.62245933 0.450166   0.52497919]


In [7]:
def relu(x):
    return np.maximum(0, x)

# Example usage
inputs = np.array([0.5, -0.2, 0.1])
outputs = relu(inputs)
print("ReLU Outputs:", outputs)


ReLU Outputs: [0.5 0.  0.1]


In [2]:
import numpy as np
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

# Example usage
inputs = np.array([0.5, -0.2, 0.1])
outputs = leaky_relu(inputs)
print("Leaky ReLU Outputs:", outputs)


Leaky ReLU Outputs: [ 0.5   -0.002  0.1  ]


In [3]:
import numpy as np

# Sigmoid Activation Function and its Derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Initialize random weights for the network
np.random.seed(42)  # For reproducibility

# Inputs (2 input features in this example)
X = np.array([[0.35, 0.7]])

# Target output
y_true = np.array([[0.5]])

# Random weights initialization
weights_input_hidden = np.random.rand(2, 2)  # Weights for input to hidden layer (2 inputs -> 2 neurons)
weights_hidden_output = np.random.rand(2, 1)  # Weights for hidden layer to output layer (2 neurons -> 1 output)

# Biases for hidden layer and output layer
bias_hidden = np.random.rand(1, 2)
bias_output = np.random.rand(1, 1)

# Step 1: Forward Propagation

# Compute weighted sums at the hidden layer
a1 = np.dot(X, weights_input_hidden) + bias_hidden  # Input to hidden layer

# Apply sigmoid activation function at hidden layer
y3 = sigmoid(a1)  # Output from hidden layer

# Compute weighted sum at the output layer
a2 = np.dot(y3, weights_hidden_output) + bias_output  # Hidden to output layer

# Apply sigmoid activation at output layer
y_pred = sigmoid(a2)  # Final output prediction

print("Output Prediction (y_pred):")
print(y_pred)

# Step 2: Backward Propagation

# Calculate the error (difference between predicted output and true output)
error = y_true - y_pred

# Compute the derivative of the sigmoid function at the output layer
delta_output = error * sigmoid_derivative(y_pred)

# Compute gradients for weights between hidden and output layer
grad_weights_hidden_output = np.dot(y3.T, delta_output)

# Compute the derivative of the sigmoid function at the hidden layer
delta_hidden = delta_output.dot(weights_hidden_output.T) * sigmoid_derivative(y3)

# Compute gradients for weights between input and hidden layer
grad_weights_input_hidden = np.dot(X.T, delta_hidden)

# Learning rate
learning_rate = 1

# Update weights and biases using the gradient descent rule
weights_input_hidden += learning_rate * grad_weights_input_hidden
weights_hidden_output += learning_rate * grad_weights_hidden_output
bias_hidden += learning_rate * np.sum(delta_hidden, axis=0, keepdims=True)
bias_output += learning_rate * np.sum(delta_output, axis=0, keepdims=True)

# Print updated weights and biases
print("\nUpdated Weights and Biases:")
print("Updated Weights between Input and Hidden Layer:")
print(weights_input_hidden)
print("Updated Weights between Hidden and Output Layer:")
print(weights_hidden_output)
print("Updated Biases for Hidden Layer:")
print(bias_hidden)
print("Updated Bias for Output Layer:")
print(bias_output)


Output Prediction (y_pred):
[[0.69753753]]

Updated Weights and Biases:
Updated Weights between Input and Hidden Layer:
[[0.37403581 0.95040007]
 [0.73098533 0.59803002]]
Updated Weights between Hidden and Output Layer:
[[0.12815659]
 [0.12121496]]
Updated Biases for Hidden Layer:
[[0.05664274 0.86527833]]
Updated Bias for Output Layer:
[[0.55943876]]


In [5]:
# Actual and predicted outputs
y_true = 0.5  # Actual output
y_pred = 0.67  # Predicted output

# Step 2: Error Calculation (using Mean Squared Error)
error = y_true - y_pred

# Printing the error
print("The error is:", error)


The error is: -0.17000000000000004


In [6]:
import numpy as np

# Sigmoid Activation Function and its Derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Initialize random weights for the network
np.random.seed(42)  # For reproducibility

# Inputs (2 input features in this example)
X = np.array([[0.35, 0.7]])

# Target output
y_true = np.array([[0.5]])

# Random weights initialization
weights_input_hidden = np.random.rand(2, 2)  # Weights for input to hidden layer (2 inputs -> 2 neurons)
weights_hidden_output = np.random.rand(2, 1)  # Weights for hidden layer to output layer (2 neurons -> 1 output)

# Biases for hidden layer and output layer
bias_hidden = np.random.rand(1, 2)
bias_output = np.random.rand(1, 1)

# Step 1: Forward Propagation

# Compute weighted sums at the hidden layer
a1 = np.dot(X, weights_input_hidden) + bias_hidden  # Input to hidden layer

# Apply sigmoid activation function at hidden layer
y3 = sigmoid(a1)  # Output from hidden layer

# Compute weighted sum at the output layer
a2 = np.dot(y3, weights_hidden_output) + bias_output  # Hidden to output layer

# Apply sigmoid activation at output layer
y_pred = sigmoid(a2)  # Final output prediction

print("Output Prediction (y_pred):", y_pred)

# Step 2: Error Calculation
error = y_true - y_pred  # Calculate error between predicted and true output

# Step 3: Backpropagation

# Compute the derivative of the sigmoid function at the output layer
delta_output = error * sigmoid_derivative(y_pred)  # Output layer error

# Compute gradients for weights between hidden and output layer
grad_weights_hidden_output = np.dot(y3.T, delta_output)

# Compute the derivative of the sigmoid function at the hidden layer
delta_hidden = delta_output.dot(weights_hidden_output.T) * sigmoid_derivative(y3)  # Hidden layer error

# Compute gradients for weights between input and hidden layer
grad_weights_input_hidden = np.dot(X.T, delta_hidden)

# Step 4: Weight Updates

# Learning rate
learning_rate = 1

# Update weights and biases using gradient descent rule
weights_input_hidden += learning_rate * grad_weights_input_hidden
weights_hidden_output += learning_rate * grad_weights_hidden_output
bias_hidden += learning_rate * np.sum(delta_hidden, axis=0, keepdims=True)
bias_output += learning_rate * np.sum(delta_output, axis=0, keepdims=True)

# Printing updated weights and biases
print("\nUpdated Weights and Biases:")
print("Updated Weights between Input and Hidden Layer:")
print(weights_input_hidden)
print("Updated Weights between Hidden and Output Layer:")
print(weights_hidden_output)
print("Updated Biases for Hidden Layer:")
print(bias_hidden)
print("Updated Bias for Output Layer:")
print(bias_output)


Output Prediction (y_pred): [[0.69753753]]

Updated Weights and Biases:
Updated Weights between Input and Hidden Layer:
[[0.37403581 0.95040007]
 [0.73098533 0.59803002]]
Updated Weights between Hidden and Output Layer:
[[0.12815659]
 [0.12121496]]
Updated Biases for Hidden Layer:
[[0.05664274 0.86527833]]
Updated Bias for Output Layer:
[[0.55943876]]


In [7]:
import numpy as np

# Sigmoid Activation Function and its Derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# XOR Dataset (inputs and outputs)
# Inputs: 4 samples with 2 features each
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Target Output: XOR output
y = np.array([[0], [1], [1], [0]])

# Initialize random weights for the network
np.random.seed(42)  # For reproducibility

# Weights for input to hidden layer (2 inputs -> 4 neurons)
weights_input_hidden = np.random.rand(2, 4)

# Weights for hidden to output layer (4 neurons -> 1 output)
weights_hidden_output = np.random.rand(4, 1)

# Biases for hidden layer and output layer
bias_hidden = np.random.rand(1, 4)
bias_output = np.random.rand(1, 1)

# Learning rate
learning_rate = 1

# Training the network
epochs = 10000
for epoch in range(epochs):
    # Step 1: Forward Propagation
    # Compute weighted sums at the hidden layer
    hidden_input = np.dot(X, weights_input_hidden) + bias_hidden
    
    # Apply sigmoid activation function at hidden layer
    hidden_output = sigmoid(hidden_input)
    
    # Compute weighted sum at the output layer
    final_input = np.dot(hidden_output, weights_hidden_output) + bias_output
    
    # Apply sigmoid activation at output layer
    y_pred = sigmoid(final_input)
    
    # Step 2: Error Calculation (Mean Squared Error)
    error = y - y_pred
    
    # Step 3: Backpropagation (Gradient Calculation)
    
    # Compute delta for output layer
    delta_output = error * sigmoid_derivative(y_pred)
    
    # Compute gradients for weights between hidden and output layer
    grad_weights_hidden_output = np.dot(hidden_output.T, delta_output)
    
    # Compute delta for hidden layer
    delta_hidden = delta_output.dot(weights_hidden_output.T) * sigmoid_derivative(hidden_output)
    
    # Compute gradients for weights between input and hidden layer
    grad_weights_input_hidden = np.dot(X.T, delta_hidden)
    
    # Step 4: Weight Updates (Gradient Descent)
    weights_input_hidden += learning_rate * grad_weights_input_hidden
    weights_hidden_output += learning_rate * grad_weights_hidden_output
    bias_hidden += learning_rate * np.sum(delta_hidden, axis=0, keepdims=True)
    bias_output += learning_rate * np.sum(delta_output, axis=0, keepdims=True)

    # Print the loss every 1000 epochs for tracking progress
    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))  # Mean Squared Error
        print(f'Epoch {epoch}, Loss: {loss}')

# Final output after training
print("\nFinal Output after Training:")
print(y_pred)



Epoch 0, Loss: 0.38554734413938047
Epoch 1000, Loss: 0.0024675076107127966
Epoch 2000, Loss: 0.0007644181764833406
Epoch 3000, Loss: 0.00043493074410382384
Epoch 4000, Loss: 0.00030022467164540756
Epoch 5000, Loss: 0.00022792807267587936
Epoch 6000, Loss: 0.00018310926728464853
Epoch 7000, Loss: 0.00015271509218649898
Epoch 8000, Loss: 0.0001307982054871689
Epoch 9000, Loss: 0.00011427255120478843

Final Output after Training:
[[0.01098264]
 [0.98876484]
 [0.99187561]
 [0.00962912]]


In [8]:
import numpy as np

# Actual and predicted values
y_true = np.array([3.0, -0.5, 2.0, 7.0])
y_pred = np.array([2.5, 0.0, 2.1, 7.8])

# Compute Mean Squared Error
mse = np.mean((y_true - y_pred) ** 2)
print("Mean Squared Error:", mse)


Mean Squared Error: 0.2874999999999999


In [ ]:
import tensorflow as tf

# Actual (binary labels) and predicted probabilities
y_true = [1, 0, 1, 1]
y_pred = [0.9, 0.2, 0.8, 0.7]

# Compute binary cross-entropy
bce_loss = tf.keras.losses.BinaryCrossentropy()
loss = bce_loss(y_true, y_pred).numpy()

print("Binary Cross-Entropy Loss:", loss)


In [10]:
from sklearn.metrics import hinge_loss

# True labels (+1 or -1 for binary classification)
y_true = np.array([1, -1, 1, -1])

# Predicted raw scores
y_pred = np.array([0.8, -0.9, 0.7, -0.6])

# Compute hinge loss
loss = hinge_loss(y_true, y_pred)

print("Hinge Loss:", loss)


Hinge Loss: 0.25
